# Generated by Django 4.0.6 on 2022-08-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LINK',
            fields=[
                ('encurtado_url', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('original_url', models.CharField(max_length=100)),
            ],
        ),
    ]
